version: '3.2'

services:
  mongo:
    image: mongo:5.0.3
    container_name: nestjs-boilerplate-mongo
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:6.2.5-alpine
    container_name: nestjs-boilerplate-redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
        - redis